mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('todo.urls')),
    url(r'^todo/', include('todo.urls')),
    url(r'^admin/', admin.site.urls),
]

todo/urls.py
from django.conf.urls import url
from . import views

app_name = 'todo'
urlpatterns = [
    # ex: /polls/
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login, name='login'),
    url(r'^login/(?P<accion>[0-1]+)$', views.loginval, name='loginval'),
    url(r'^login/exit/$', views.logindel, name='logindel'),
    url(r'^register/$', views.register, name='register'),
    url(r'^register/(?P<accion>[0-1]+)$', views.registerval, name='registerval'),
    url(r'^create/$', views.create, name='create'),
    url(r'^create/(?P<id>[0-9999999999]+)$', views.createval, name='createval'),
    url(r'^list/$', views.list, name='list'),
    url(r'^edit/(?P<id>[0-9999999999]+)$', views.edit, name='edit'),
    url(r'^edit/change/(?P<id>[0-9999999999]+)$', views.editval, name='editval'),
    url(r'^delete/(?P<id>[0-9999999999]+)$', views.delete, name='delete'),
    url(r'^edituser/$', views.edituser, name='edituser'),
    url(r'^edituser/change/$', views.edituserval, name='edituserval')
    # url(r'^$', views.RegisterView.as_view(), name='register')
    # ex: /polls/5/
    # url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # ex: /polls/5/results/
    # url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    # ex: /polls/5/vote/
    # url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote')
]

todo/models.py
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

# Create your models here.
@python_2_unicode_compatible  # only if you need to support Python 2
class Usuario(models.Model):
    nombreusuario = models.CharField(max_length=50, unique=True)
    password = models.CharField(max_length=50)
    nombre = models.CharField(max_length=200)
    apellido = models.CharField(max_length=200)
    email = models.EmailField(max_length=200)
    creado = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.nombreusuario

@python_2_unicode_compatible  # only if you need to support Python 2
class Nota(models.Model):
    usuario = models.ForeignKey('Usuario', on_delete=models.CASCADE)
    titulo = models.TextField(max_length=200)
    texto = models.TextField(max_length=200)
    creado = models.DateTimeField(auto_now_add=True)
    publico = models.BooleanField(default=False)

    def es_reciente(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now

    def __str__(self):
        return self.titulo

todo/views.py
# Create your views here.
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from django.template import loader
from django.core.exceptions import ObjectDoesNotExist
import json
from .models import Usuario, Nota

def index(request):

    nota_list = Nota.objects.filter( publico = True ).order_by('-creado')[:10]
    usuario = request.session.get( 'usuario', 'NONAME' )
    return render( request, 'todo/index.html', {
        'nota_list': nota_list,
        'usuario': usuario
    } )

def login(request):
    usuario = request.session.get('usuario', 'NONAME' )
    if usuario == 'NONAME' or usuario == '':
        return render( request, 'todo/login.html', None )
    return HttpResponseRedirect(reverse('todo:index'))

def loginval(request, accion):
    try:
        o_usuario = Usuario.objects.get(nombreusuario = request.POST['nombreusuario'], password = request.POST['password'] )
    except:
        return render( request, 'todo/login.html', {
            'error_message': "Las credenciales son incorrectas. Por favor vuelva a intentar..."
        })
    else:
        request.session['usuario'] = o_usuario.nombreusuario
        return render( request, 'todo/index.html', context = {
            'nota_list': Nota.objects.filter( publico = True ).order_by('-creado')[:10],
            'usuario': o_usuario.nombreusuario
        } )

def logindel(request):
    del request.session['usuario']
    request.session.modified = True
    return render( request, 'todo/index.html', context = {
        'nota_list': Nota.objects.filter( publico = True ).order_by('-creado')[:10],
        'usuario': 'NONAME'
    } )

def register(request):
    usuario = request.session.get('usuario', 'NONAME' )
    return render( request, 'todo/register.html', context = {
        'usuario': usuario
    } )

def registerval(request, accion):
    try:
        o_usuario = Usuario(
            nombreusuario = request.POST['nombreusuario'],
            password = request.POST['password'],
            nombre = request.POST['nombre'],
            apellido = request.POST['apellido'],
            email = request.POST['email']
        )
        o_usuario.save()
    except:
        return render( request, 'todo/register.html', {
            'error_message': "Los datos son incorrectos. Por favor vuelva a intentar..."
        })
    else:
        request.session['usuario'] = o_usuario.nombreusuario
        return render( request, 'todo/index.html', {
            'nota_list': Nota.objects.filter( publico = True ).order_by('-creado')[:10],
            'usuario': o_usuario.nombreusuario
        } )

def create(request):
    usuario = request.session.get('usuario', 'NONAME' )
    if usuario == 'NONAME' or usuario == '':
        return HttpResponseRedirect(reverse('todo:index'))
    return render( request, 'todo/create.html', { 'usuario' : usuario } )

def createval(request, id):
    usuario = request.session.get('usuario', 'NONAME' )
    if usuario == 'NONAME' or usuario == '':
        return HttpResponseRedirect(reverse('todo:index'))

    pub = True
    try:
        if request.POST['publico'] == None:
            pub = False
    except:
        pub = False

    try:
        o_usuario = Usuario.objects.get(nombreusuario=usuario)
        o_usuario.nota_set.create(texto=request.POST['texto'], titulo=request.POST['titulo'], publico=pub )
    except:
        return render( request, 'todo/create.html', {
            'error_message': 'Error al grabar registro...',
            'usuario': usuario
        } )
    return HttpResponseRedirect(reverse('todo:index'))

def list(request):
    usuario = request.session.get('usuario', 'NONAME' )
    if usuario == 'NONAME' or usuario == '':
        return HttpResponseRedirect(reverse('todo:index'))
    nota_list = Nota.objects.filter( usuario__nombreusuario=usuario ).order_by('-creado')
    return render( request, 'todo/list.html', {
        'nota_list': nota_list,
        'usuario': usuario
    } )

def edit(request, id):
    usuario = request.session.get('usuario', 'NONAME' )
    if usuario == 'NONAME' or usuario == '':
        return HttpResponseRedirect(reverse('todo:index'))
    o_nota = Nota.objects.get(pk=id)
    return render( request, 'todo/edit.html', {
        'nota': o_nota,
        'usuario': usuario
    } )

def editval(request, id):
    usuario = request.session.get('usuario', 'NONAME' )
    if usuario == 'NONAME' or usuario == '':
        return HttpResponseRedirect(reverse('todo:index'))
    ## CODIGO PROPIO
    o_nota = Nota.objects.get(pk=id)

    pub = True
    try:
        if request.POST['publico'] == None:
            pub = False
    except:
        pub = False

    o_nota.texto = request.POST['texto']
    o_nota.titulo = request.POST['titulo']
    o_nota.publico = pub
    o_nota.save()
    ## #################
    nota_list = Nota.objects.filter( usuario__nombreusuario=usuario ).order_by('-creado')
    return render( request, 'todo/list.html', {
        'nota_list': nota_list,
        'usuario': usuario
    } )

def delete(request, id):
    usuario = request.session.get('usuario', 'NONAME' )
    if usuario == 'NONAME' or usuario == '':
        return HttpResponseRedirect(reverse('todo:index'))
    ## CODIGO PROPIO
    o_nota = Nota.objects.get(pk=id)
    o_nota.delete()
    ## #################
    nota_list = Nota.objects.filter( usuario__nombreusuario=usuario ).order_by('-creado')
    return render( request, 'todo/list.html', {
        'nota_list': nota_list,
        'usuario': usuario
    } )

def edituser(request):
    usuario = request.session.get('usuario', 'NONAME' )
    if usuario == 'NONAME':
        return HttpResponseRedirect(reverse('todo:index'))
    o_usuario = Usuario.objects.get(nombreusuario=usuario)
    return render( request, 'todo/edituser.html', {
        'usuario': o_usuario
    } )

def edituserval(request):
    usuario = request.session.get('usuario', 'NONAME' )
    if usuario == 'NONAME':
        return HttpResponseRedirect(reverse('todo:index'))
    o_usuario = Usuario.objects.get(nombreusuario=usuario)
    try:
        o_usuario.password = request.POST['password']
        o_usuario.nombre = request.POST['nombre']
        o_usuario.apellido = request.POST['apellido']
        o_usuario.email = request.POST['email']
        o_usuario.save()
    except:
        return render( request, 'todo/edituser.html', {
            'error_message': "Los datos son incorrectos. Por favor vuelva a intentar...",
            'usuario': o_usuario
        })
    else:
        return HttpResponseRedirect(reverse('todo:index'))

todo/templates/todo/create.html
<!doctype html>
<html lang="en">
{% load static %}
<HEAD>
    <title>NOTAS :: CREAR NUEVA NOTA</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'todo/css/bootstrap.min.css' %}" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'todo/css/jumbotron.css' %}">
</HEAD>
<BODY>

  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">TO-DO</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todo:index' %}">Home <span class="sr-only">(current)</span></a>
        </li>

        {% if usuario == 'NONAME' or usuario == '' %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todo:login' %}">Login</a>
        {% else %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="menu" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Mi Cuenta</a>
          <div class="dropdown-menu" aria-labelledby="menu">
                <a class="dropdown-item" href="#">Usuario: {{ usuario }}</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'todo:edituser' %}">Mis Datos</a>
                <a class="dropdown-item" href="{% url 'todo:logindel' %}">Cerrar Sesion</a>
          </div>
          {% endif %}
        </li>
        {% if usuario != 'NONAME' and usuario != '' %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="menu2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Notas</a>
          <div class="dropdown-menu" aria-labelledby="menu2">
                <a class="dropdown-item" href="{% url 'todo:create' %}">Nueva</a>
                <a class="dropdown-item" href="{% url 'todo:list' %}">Mis Notas</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'todo:index' %}">Todas las Notas</a>
          </div>
        </li>
        {% endif %}
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

  {% if error_message %}
  <p><strong>{{ error_message }}</strong></p>
  {% endif %}

  <main role="main">
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1 class="display-3">Crear Nueva Nota</h1>
        <p>Ingrese sus datos</p>
        <p><a class="btn btn-secondary btn-lg" href="#" role="button">Sepa más &raquo;</a></p>
      </div>
    </div>

    <div class="container">
      <form action="{% url 'todo:createval' 1 %}" method="post">
      {% csrf_token %}
        <div class="form-group row">
          <label class="col-sm-2 col-form-label" for="titulo">Titulo</label>
          <div class="col-sm-10">
            <input class="form-control mx-sm-3" type="text" name="titulo" id="titulo" value="" />
            <small id="textoHelp" class="form-text text-muted">Máximo 50 caracteres.</small>
          </div>
        </div>

        <div class="form-group row">
          <label class="col-sm-2 col-form-label" for="texto">Texto</label>
          <div class="col-sm-10">
            <input class="form-control mx-sm-3" type="text" name="texto" id="texto" value="" />
            <small id="textoHelp" class="form-text text-muted">Máximo 200 caracteres.</small>
          </div>
        </div>

        <div class="form-group row">
          <label class="col-sm-2 col-form-label" for="publico">Es Publico?</label>
          <div class="col-sm-10">
            <input type="checkbox" class="form-control mx-sm-3" name="publico" id="publico" checked />
            <small id="publicoHelp" class="form-text text-muted ">Seleccione si la nota será visible para los demas usuarios</small>
          </div>
        </div>

        <input type="submit" class="btn btn-primary" value="Crear Nota" />
      </form>
    </div>

  </main>

  <footer class="container">
      <p></p><p></p>
      <p>&copy; Alessandro Chipulina</p>
  </footer>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="{% static 'todo/js/jquery-3.2.1.slim.min.js' %}" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="{% static 'todo/js/popper.min.js' %}" ></script>
  <script src="{% static 'todo/js/bootstrap.min.js' %}" ></script>

</BODY>
</HTML>

todo/templates/todo/edit.html
<!doctype html>
<html lang="en">
{% load static %}
<HEAD>
    <title>NOTAS :: EDITAR NOTA</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'todo/css/bootstrap.min.css' %}" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'todo/css/jumbotron.css' %}">
</HEAD>
<BODY>

  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">TO-DO</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todo:index' %}">Home <span class="sr-only">(current)</span></a>
        </li>

        {% if usuario == 'NONAME' or usuario == '' %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todo:login' %}">Login</a>
        {% else %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="menu" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Mi Cuenta</a>
          <div class="dropdown-menu" aria-labelledby="menu">
                <a class="dropdown-item" href="#">Usuario: {{ usuario }}</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'todo:edituser' %}">Mis Datos</a>
                <a class="dropdown-item" href="{% url 'todo:logindel' %}">Cerrar Sesion</a>
          </div>
          {% endif %}
        </li>
        {% if usuario != 'NONAME' and usuario != '' %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="menu2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Notas</a>
          <div class="dropdown-menu" aria-labelledby="menu2">
                <a class="dropdown-item" href="{% url 'todo:create' %}">Nueva</a>
                <a class="dropdown-item" href="{% url 'todo:list' %}">Mis Notas</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'todo:index' %}">Todas las Notas</a>
          </div>
        </li>
        {% endif %}
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

  {% if error_message %}
  <p><strong>{{ error_message }}</strong></p>
  {% endif %}

  <main role="main">
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1 class="display-3">Editar Nota</h1>
        <p>Actualice los datos de la nota.</p>
        <p><a class="btn btn-secondary btn-lg" href="#" role="button">Sepa más &raquo;</a></p>
      </div>
    </div>

    <div class="container">
      <form action="{% url 'todo:editval' id=nota.id %}" method="post">
      {% csrf_token %}
        <div class="form-group row">
          <label class="col-sm-2 col-form-label" for="titulo">Titulo</label>
          <div class="col-sm-10">
            <input class="form-control mx-sm-3" type="text" name="titulo" id="titulo" value="{{ nota.titulo }}" />
            <small id="textoHelp" class="form-text text-muted">Máximo 50 caracteres.</small>
          </div>
        </div>

        <div class="form-group row">
          <label class="col-sm-2 col-form-label" for="texto">Texto</label>
          <div class="col-sm-10">
            <input class="form-control mx-sm-3" type="text" name="texto" id="texto" value="{{ nota.texto }}" />
            <small id="textoHelp" class="form-text text-muted">Máximo 200 caracteres.</small>
          </div>
        </div>

        <div class="form-group row">
          <label class="col-sm-2 col-form-label" for="publico">Es Publico?</label>
          <div class="col-sm-10">
            <input type="checkbox" class="form-control mx-sm-3" name="publico" id="publico"
            {% if nota.publico == True %}
            checked
            {% endif %}
            />
            <small id="publicoHelp" class="form-text text-muted ">Seleccione si la nota será visible para los demas usuarios</small>
          </div>
        </div>

        <input type="submit" class="btn btn-primary" value="Editar Nota" />
      </form>
    </div>

  </main>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="{% static 'todo/js/jquery-3.2.1.slim.min.js' %}" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="{% static 'todo/js/popper.min.js' %}" ></script>
  <script src="{% static 'todo/js/bootstrap.min.js' %}" ></script>

</BODY>
</HTML>

todo/templates/todo/list.html
<!doctype html>
<html lang="en">
{% load static %}
<HEAD>
    <title>NOTAS :: MIS NOTAS</title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'todo/css/bootstrap.min.css' %}" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'todo/css/jumbotron.css' %}">
</HEAD>
<BODY>

  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">TO-DO</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExampleDefault">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todo:index' %}">Home <span class="sr-only">(current)</span></a>
        </li>

        {% if usuario == 'NONAME' or usuario == '' %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todo:login' %}">Login</a>
        {% else %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="menu" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">Mi Cuenta</a>
          <div class="dropdown-menu" aria-labelledby="menu">
                <a class="dropdown-item" href="#">Usuario: {{ usuario }}</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{% url 'todo:edituser' %}">Mis Datos</a>
                <a class="dropdown-item" href="{% url 'todo:logindel' %}">Cerrar Sesion</a>
          </div>
          {% endif %}
        </li>
        {% if usuario != 'NONAME' and usuario != '' %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="menu2" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Notas</a>
          <div class="dropdown-menu" aria-labelledby="menu2">
                <a class="dropdown-item" href="{% url 'todo:create' %}">Nueva</a>
                <a class="dropdown-item" href="{% url 'todo:index' %}">Ver Todas</a>
          </div>
        </li>
        {% endif %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'todo:register' %}">Nuevo Usuario</a>
        </li>
      </ul>
      <form class="form-inline my-2 my-lg-0">
        <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
      </form>
    </div>
  </nav>

  <main role="main">
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1 class="display-3">Todas Mis Notas</h1>
        <p>Revise todas tus notas. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique.</p>
        <p><a class="btn btn-secondary btn-lg" href="#" role="button">Sepa más &raquo;</a></p>
      </div>
    </div>

    {% if nota_list %}
    <div class="container">
        {% for nota in nota_list %}
        {% cycle '<div class="row">' '' '' %}
          <div class="col-md-4">
            <h2>{{ nota.titulo }}</h2>
            <p>{{ nota.texto }}</p>
            <p>
              {% if nota.publico %}
              PUBLICO
              {% else %}
              PRIVADO
              {% endif %}
            </p>
            <p>
              <a class="btn btn-success btn-sm" href="{% url 'todo:edit' id=nota.id %}" role="button">Editar&raquo;</a>&nbsp;
              <a class="btn btn-danger btn-sm" href="{% url 'todo:delete' id=nota.id %}" role="button">Borrar&raquo;</a>
            </p>
            <p>{{ nota.creado }}</p>
          </div>
        {% cycle '' '' '</div>' %}
        {% endfor %}
      </div>
    </div>
    {% else %}
      <p>No existen notas disponibles</p>
    {% endif %}

  </main>

  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->
  <script src="{% static 'todo/js/jquery-3.2.1.slim.min.js' %}" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="{% static 'todo/js/popper.min.js' %}" ></script>
  <script src="{% static 'todo/js/bootstrap.min.js' %}" ></script>
</BODY>
</HTML>